services:
  rabbitmq3:
    container_name: "rabbitmq" 
    image: rabbitmq:3.8-management-alpine
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass